// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as grpcreflect$0 from "./internal/grpcreflect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateServer(name: string, address: string, useTLS: boolean, insecure: boolean): $CancellablePromise<number> {
    return $Call.ByID(3177189426, name, address, useTLS, insecure);
}

export function DeleteHistoryItem(id: number): $CancellablePromise<void> {
    return $Call.ByID(2090475737, id);
}

export function DeleteServer(id: number): $CancellablePromise<void> {
    return $Call.ByID(963928181, id);
}

export function DeleteTabState(tabID: string): $CancellablePromise<void> {
    return $Call.ByID(1010453490, tabID);
}

export function DoGRPCRequest(serverId: number, address: string, service: string, method: string, payload: string, requestHeaders: { [_ in string]?: string } | null, contextValues: { [_ in string]?: string } | null): $CancellablePromise<[string, number]> {
    return $Call.ByID(531879593, serverId, address, service, method, payload, requestHeaders, contextValues);
}

export function GetHistory(serverId: number, limit: number): $CancellablePromise<models$0.History[] | null> {
    return $Call.ByID(210907985, serverId, limit);
}

export function GetHistoryItem(id: number): $CancellablePromise<models$0.History | null> {
    return $Call.ByID(1570925930, id);
}

export function GetJsonExample(msg: grpcreflect$0.MessageInfo | null): $CancellablePromise<string> {
    return $Call.ByID(1994665097, msg);
}

export function GetServerReflection(id: number): $CancellablePromise<models$0.Server | null> {
    return $Call.ByID(3482647849, id);
}

export function GetServerWithReflection(id: number): $CancellablePromise<$models.ServerWithReflection | null> {
    return $Call.ByID(241357665, id);
}

export function GetServers(): $CancellablePromise<models$0.Server[] | null> {
    return $Call.ByID(4270553301);
}

export function GetServersWithReflection(): $CancellablePromise<$models.ServerWithReflection[] | null> {
    return $Call.ByID(3123129712);
}

export function GetTabStates(): $CancellablePromise<models$0.TabState[] | null> {
    return $Call.ByID(473154136);
}

export function SaveTabStates(tabStates: models$0.TabState[] | null): $CancellablePromise<void> {
    return $Call.ByID(4192036329, tabStates);
}

export function ToggleFavoriteServer(serverID: number): $CancellablePromise<void> {
    return $Call.ByID(372922338, serverID);
}

export function UpdateServer(id: number, name: string, address: string, useTLS: boolean, insecure: boolean): $CancellablePromise<void> {
    return $Call.ByID(3010445599, id, name, address, useTLS, insecure);
}

export function ValidateServerAddress(address: string, useTLS: boolean, insecure: boolean): $CancellablePromise<$models.ValidationResult> {
    return $Call.ByID(3191889264, address, useTLS, insecure);
}
