// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ValidationResult {
    "status": ValidationStatus;
    "message"?: string;
}

export enum ValidationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ValidationStatusSuccess = 0,
    ValidationStatusConnectionFailed = 1,
    ValidationStatusReflectionNotAvailable = 2,
    ValidationStatusNoServices = 3,
};
