// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as grpcreflect$0 from "./internal/grpcreflect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

export interface ServerWithReflection {
    "server": models$0.Server | null;
    "reflection": grpcreflect$0.ServicesInfo | null;
    "error"?: string;
}

export interface ValidationResult {
    "status": ValidationStatus;
    "message"?: string;
}

export enum ValidationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ValidationStatusSuccess = 0,
    ValidationStatusConnectionFailed = 1,
    ValidationStatusReflectionNotAvailable = 2,
    ValidationStatusNoServices = 3,
};
