// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/test.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN  Status = 0
	Status_PENDING  Status = 1
	Status_ACTIVE   Status = 2
	Status_INACTIVE Status = 3
	Status_DELETED  Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "ACTIVE",
		3: "INACTIVE",
		4: "DELETED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"ACTIVE":   2,
		"INACTIVE": 3,
		"DELETED":  4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_test_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_test_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{0}
}

type Priority int32

const (
	Priority_LOW      Priority = 0
	Priority_MEDIUM   Priority = 1
	Priority_HIGH     Priority = 2
	Priority_CRITICAL Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		2: "HIGH",
		3: "CRITICAL",
	}
	Priority_value = map[string]int32{
		"LOW":      0,
		"MEDIUM":   1,
		"HIGH":     2,
		"CRITICAL": 3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_test_proto_enumTypes[1].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_proto_test_proto_enumTypes[1]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{1}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	ZipCode       int32                  `protobuf:"varint,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Balance       float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Score         float32                `protobuf:"fixed32,6,opt,name=score,proto3" json:"score,omitempty"`
	Age           int32                  `protobuf:"varint,7,opt,name=age,proto3" json:"age,omitempty"`
	Points        uint32                 `protobuf:"varint,8,opt,name=points,proto3" json:"points,omitempty"`
	SignedPoints  int32                  `protobuf:"zigzag32,9,opt,name=signed_points,json=signedPoints,proto3" json:"signed_points,omitempty"`
	FixedId       uint64                 `protobuf:"fixed64,10,opt,name=fixed_id,json=fixedId,proto3" json:"fixed_id,omitempty"`
	SfixedValue   int32                  `protobuf:"fixed32,11,opt,name=sfixed_value,json=sfixedValue,proto3" json:"sfixed_value,omitempty"`
	Avatar        []byte                 `protobuf:"bytes,12,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        Status                 `protobuf:"varint,13,opt,name=status,proto3,enum=testserver.Status" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers       []int32                `protobuf:"varint,15,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Address       *Address               `protobuf:"bytes,16,opt,name=address,proto3" json:"address,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,17,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AddressMap    map[int32]*Address     `protobuf:"bytes,18,rep,name=address_map,json=addressMap,proto3" json:"address_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Addresses     []*Address             `protobuf:"bytes,19,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetPoints() uint32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *User) GetSignedPoints() int32 {
	if x != nil {
		return x.SignedPoints
	}
	return 0
}

func (x *User) GetFixedId() uint64 {
	if x != nil {
		return x.FixedId
	}
	return 0
}

func (x *User) GetSfixedValue() int32 {
	if x != nil {
		return x.SfixedValue
	}
	return 0
}

func (x *User) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *User) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetAddressMap() map[int32]*Address {
	if x != nil {
		return x.AddressMap
	}
	return nil
}

func (x *User) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nested        *NestedMessage         `protobuf:"bytes,2,opt,name=nested,proto3" json:"nested,omitempty"`
	Children      []*NestedMessage       `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_proto_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{2}
}

func (x *NestedMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedMessage) GetNested() *NestedMessage {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *NestedMessage) GetChildren() []*NestedMessage {
	if x != nil {
		return x.Children
	}
	return nil
}

type ComplexRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	User      *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users     []*User                `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	UserMap   map[string]*User       `protobuf:"bytes,3,rep,name=user_map,json=userMap,proto3" json:"user_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Nested    *NestedMessage         `protobuf:"bytes,4,opt,name=nested,proto3" json:"nested,omitempty"`
	Status    Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=testserver.Status" json:"status,omitempty"`
	Statuses  []Status               `protobuf:"varint,6,rep,packed,name=statuses,proto3,enum=testserver.Status" json:"statuses,omitempty"`
	StatusMap map[string]Status      `protobuf:"bytes,7,rep,name=status_map,json=statusMap,proto3" json:"status_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=testserver.Status"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ComplexRequest_Text
	//	*ComplexRequest_Number
	//	*ComplexRequest_UserPayload
	Payload       isComplexRequest_Payload `protobuf_oneof:"payload"`
	Timestamps    []int64                  `protobuf:"varint,11,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	Prices        []float64                `protobuf:"fixed64,12,rep,packed,name=prices,proto3" json:"prices,omitempty"`
	Flags         []bool                   `protobuf:"varint,13,rep,packed,name=flags,proto3" json:"flags,omitempty"`
	IdToName      map[int64]string         `protobuf:"bytes,14,rep,name=id_to_name,json=idToName,proto3" json:"id_to_name,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RawData       []byte                   `protobuf:"bytes,15,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexRequest) Reset() {
	*x = ComplexRequest{}
	mi := &file_proto_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexRequest) ProtoMessage() {}

func (x *ComplexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexRequest.ProtoReflect.Descriptor instead.
func (*ComplexRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{3}
}

func (x *ComplexRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ComplexRequest) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ComplexRequest) GetUserMap() map[string]*User {
	if x != nil {
		return x.UserMap
	}
	return nil
}

func (x *ComplexRequest) GetNested() *NestedMessage {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *ComplexRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *ComplexRequest) GetStatuses() []Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ComplexRequest) GetStatusMap() map[string]Status {
	if x != nil {
		return x.StatusMap
	}
	return nil
}

func (x *ComplexRequest) GetPayload() isComplexRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ComplexRequest) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*ComplexRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ComplexRequest) GetNumber() int32 {
	if x != nil {
		if x, ok := x.Payload.(*ComplexRequest_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *ComplexRequest) GetUserPayload() *User {
	if x != nil {
		if x, ok := x.Payload.(*ComplexRequest_UserPayload); ok {
			return x.UserPayload
		}
	}
	return nil
}

func (x *ComplexRequest) GetTimestamps() []int64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *ComplexRequest) GetPrices() []float64 {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *ComplexRequest) GetFlags() []bool {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ComplexRequest) GetIdToName() map[int64]string {
	if x != nil {
		return x.IdToName
	}
	return nil
}

func (x *ComplexRequest) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type isComplexRequest_Payload interface {
	isComplexRequest_Payload()
}

type ComplexRequest_Text struct {
	Text string `protobuf:"bytes,8,opt,name=text,proto3,oneof"`
}

type ComplexRequest_Number struct {
	Number int32 `protobuf:"varint,9,opt,name=number,proto3,oneof"`
}

type ComplexRequest_UserPayload struct {
	UserPayload *User `protobuf:"bytes,10,opt,name=user_payload,json=userPayload,proto3,oneof"`
}

func (*ComplexRequest_Text) isComplexRequest_Payload() {}

func (*ComplexRequest_Number) isComplexRequest_Payload() {}

func (*ComplexRequest_UserPayload) isComplexRequest_Payload() {}

type ComplexResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	User          *User                    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users         []*User                  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Results       map[string]*User         `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        Status                   `protobuf:"varint,4,opt,name=status,proto3,enum=testserver.Status" json:"status,omitempty"`
	Messages      []string                 `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	Count         int32                    `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Total         float64                  `protobuf:"fixed64,7,opt,name=total,proto3" json:"total,omitempty"`
	Nested        *NestedMessage           `protobuf:"bytes,8,opt,name=nested,proto3" json:"nested,omitempty"`
	Tree          []*NestedMessage         `protobuf:"bytes,9,rep,name=tree,proto3" json:"tree,omitempty"`
	Nodes         map[int32]*NestedMessage `protobuf:"bytes,10,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexResponse) Reset() {
	*x = ComplexResponse{}
	mi := &file_proto_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexResponse) ProtoMessage() {}

func (x *ComplexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexResponse.ProtoReflect.Descriptor instead.
func (*ComplexResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{4}
}

func (x *ComplexResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ComplexResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ComplexResponse) GetResults() map[string]*User {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ComplexResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *ComplexResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ComplexResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ComplexResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ComplexResponse) GetNested() *NestedMessage {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *ComplexResponse) GetTree() []*NestedMessage {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *ComplexResponse) GetNodes() map[int32]*NestedMessage {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SimpleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleRequest) Reset() {
	*x = SimpleRequest{}
	mi := &file_proto_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRequest) ProtoMessage() {}

func (x *SimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRequest.ProtoReflect.Descriptor instead.
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{5}
}

func (x *SimpleRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SimpleRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Processed     int32                  `protobuf:"varint,2,opt,name=processed,proto3" json:"processed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	mi := &file_proto_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{6}
}

func (x *SimpleResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *SimpleResponse) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{7}
}

func (x *StreamRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=testserver.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_proto_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{8}
}

func (x *StreamResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *StreamResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{9}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_proto_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{10}
}

type ScheduleRequest struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	TaskName       string                          `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Priority       Priority                        `protobuf:"varint,2,opt,name=priority,proto3,enum=testserver.Priority" json:"priority,omitempty"`
	ScheduledAt    *timestamppb.Timestamp          `protobuf:"bytes,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	Timeout        *durationpb.Duration            `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Deadline       *timestamppb.Timestamp          `protobuf:"bytes,5,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	Status         Status                          `protobuf:"varint,6,opt,name=status,proto3,enum=testserver.Status" json:"status,omitempty"`
	Checkpoints    []*timestamppb.Timestamp        `protobuf:"bytes,7,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	PhaseDurations map[string]*durationpb.Duration `protobuf:"bytes,8,rep,name=phase_durations,json=phaseDurations,proto3" json:"phase_durations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Description    *string                         `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RetryCount     *int32                          `protobuf:"varint,10,opt,name=retry_count,json=retryCount,proto3,oneof" json:"retry_count,omitempty"`
	IsCritical     *bool                           `protobuf:"varint,11,opt,name=is_critical,json=isCritical,proto3,oneof" json:"is_critical,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_proto_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{11}
}

func (x *ScheduleRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ScheduleRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_LOW
}

func (x *ScheduleRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *ScheduleRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ScheduleRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *ScheduleRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *ScheduleRequest) GetCheckpoints() []*timestamppb.Timestamp {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

func (x *ScheduleRequest) GetPhaseDurations() map[string]*durationpb.Duration {
	if x != nil {
		return x.PhaseDurations
	}
	return nil
}

func (x *ScheduleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ScheduleRequest) GetRetryCount() int32 {
	if x != nil && x.RetryCount != nil {
		return *x.RetryCount
	}
	return 0
}

func (x *ScheduleRequest) GetIsCritical() bool {
	if x != nil && x.IsCritical != nil {
		return *x.IsCritical
	}
	return false
}

type ScheduleResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status            Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=testserver.Status" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartsAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EstimatedDuration *durationpb.Duration   `protobuf:"bytes,5,opt,name=estimated_duration,json=estimatedDuration,proto3" json:"estimated_duration,omitempty"`
	AssignedPriority  Priority               `protobuf:"varint,6,opt,name=assigned_priority,json=assignedPriority,proto3,enum=testserver.Priority" json:"assigned_priority,omitempty"`
	Message           string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_proto_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_proto_rawDescGZIP(), []int{12}
}

func (x *ScheduleResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ScheduleResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *ScheduleResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScheduleResponse) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *ScheduleResponse) GetEstimatedDuration() *durationpb.Duration {
	if x != nil {
		return x.EstimatedDuration
	}
	return nil
}

func (x *ScheduleResponse) GetAssignedPriority() Priority {
	if x != nil {
		return x.AssignedPriority
	}
	return Priority_LOW
}

func (x *ScheduleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_test_proto protoreflect.FileDescriptor

const file_proto_test_proto_rawDesc = "" +
	"\n" +
	"\x10proto/test.proto\x12\n" +
	"testserver\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"j\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\x05R\azipCode\"\xf9\x05\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x01R\abalance\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x02R\x05score\x12\x10\n" +
	"\x03age\x18\a \x01(\x05R\x03age\x12\x16\n" +
	"\x06points\x18\b \x01(\rR\x06points\x12#\n" +
	"\rsigned_points\x18\t \x01(\x11R\fsignedPoints\x12\x19\n" +
	"\bfixed_id\x18\n" +
	" \x01(\x06R\afixedId\x12!\n" +
	"\fsfixed_value\x18\v \x01(\x0fR\vsfixedValue\x12\x16\n" +
	"\x06avatar\x18\f \x01(\fR\x06avatar\x12*\n" +
	"\x06status\x18\r \x01(\x0e2\x12.testserver.StatusR\x06status\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x18\n" +
	"\anumbers\x18\x0f \x03(\x05R\anumbers\x12-\n" +
	"\aaddress\x18\x10 \x01(\v2\x13.testserver.AddressR\aaddress\x12:\n" +
	"\bmetadata\x18\x11 \x03(\v2\x1e.testserver.User.MetadataEntryR\bmetadata\x12A\n" +
	"\vaddress_map\x18\x12 \x03(\v2 .testserver.User.AddressMapEntryR\n" +
	"addressMap\x121\n" +
	"\taddresses\x18\x13 \x03(\v2\x13.testserver.AddressR\taddresses\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aR\n" +
	"\x0fAddressMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.testserver.AddressR\x05value:\x028\x01\"\x8d\x01\n" +
	"\rNestedMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x06nested\x18\x02 \x01(\v2\x19.testserver.NestedMessageR\x06nested\x125\n" +
	"\bchildren\x18\x03 \x03(\v2\x19.testserver.NestedMessageR\bchildren\"\xfb\x06\n" +
	"\x0eComplexRequest\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.testserver.UserR\x04user\x12&\n" +
	"\x05users\x18\x02 \x03(\v2\x10.testserver.UserR\x05users\x12B\n" +
	"\buser_map\x18\x03 \x03(\v2'.testserver.ComplexRequest.UserMapEntryR\auserMap\x121\n" +
	"\x06nested\x18\x04 \x01(\v2\x19.testserver.NestedMessageR\x06nested\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.testserver.StatusR\x06status\x12.\n" +
	"\bstatuses\x18\x06 \x03(\x0e2\x12.testserver.StatusR\bstatuses\x12H\n" +
	"\n" +
	"status_map\x18\a \x03(\v2).testserver.ComplexRequest.StatusMapEntryR\tstatusMap\x12\x14\n" +
	"\x04text\x18\b \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\t \x01(\x05H\x00R\x06number\x125\n" +
	"\fuser_payload\x18\n" +
	" \x01(\v2\x10.testserver.UserH\x00R\vuserPayload\x12\x1e\n" +
	"\n" +
	"timestamps\x18\v \x03(\x03R\n" +
	"timestamps\x12\x16\n" +
	"\x06prices\x18\f \x03(\x01R\x06prices\x12\x14\n" +
	"\x05flags\x18\r \x03(\bR\x05flags\x12F\n" +
	"\n" +
	"id_to_name\x18\x0e \x03(\v2(.testserver.ComplexRequest.IdToNameEntryR\bidToName\x12\x19\n" +
	"\braw_data\x18\x0f \x01(\fR\arawData\x1aL\n" +
	"\fUserMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.testserver.UserR\x05value:\x028\x01\x1aP\n" +
	"\x0eStatusMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\x0e2\x12.testserver.StatusR\x05value:\x028\x01\x1a;\n" +
	"\rIdToNameEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"\xda\x04\n" +
	"\x0fComplexResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.testserver.UserR\x04user\x12&\n" +
	"\x05users\x18\x02 \x03(\v2\x10.testserver.UserR\x05users\x12B\n" +
	"\aresults\x18\x03 \x03(\v2(.testserver.ComplexResponse.ResultsEntryR\aresults\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.testserver.StatusR\x06status\x12\x1a\n" +
	"\bmessages\x18\x05 \x03(\tR\bmessages\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12\x14\n" +
	"\x05total\x18\a \x01(\x01R\x05total\x121\n" +
	"\x06nested\x18\b \x01(\v2\x19.testserver.NestedMessageR\x06nested\x12-\n" +
	"\x04tree\x18\t \x03(\v2\x19.testserver.NestedMessageR\x04tree\x12<\n" +
	"\x05nodes\x18\n" +
	" \x03(\v2&.testserver.ComplexResponse.NodesEntryR\x05nodes\x1aL\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.testserver.UserR\x05value:\x028\x01\x1aS\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.testserver.NestedMessageR\x05value:\x028\x01\"?\n" +
	"\rSimpleRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"F\n" +
	"\x0eSimpleResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x1c\n" +
	"\tprocessed\x18\x02 \x01(\x05R\tprocessed\"3\n" +
	"\rStreamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"d\n" +
	"\x0eStreamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.testserver.StatusR\x06status\"\x0e\n" +
	"\fEmptyRequest\"\x0f\n" +
	"\rEmptyResponse\"\xe3\x05\n" +
	"\x0fScheduleRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x120\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x14.testserver.PriorityR\bpriority\x12=\n" +
	"\fscheduled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12;\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdeadline\x88\x01\x01\x12*\n" +
	"\x06status\x18\x06 \x01(\x0e2\x12.testserver.StatusR\x06status\x12<\n" +
	"\vcheckpoints\x18\a \x03(\v2\x1a.google.protobuf.TimestampR\vcheckpoints\x12X\n" +
	"\x0fphase_durations\x18\b \x03(\v2/.testserver.ScheduleRequest.PhaseDurationsEntryR\x0ephaseDurations\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x01R\vdescription\x88\x01\x01\x12$\n" +
	"\vretry_count\x18\n" +
	" \x01(\x05H\x02R\n" +
	"retryCount\x88\x01\x01\x12$\n" +
	"\vis_critical\x18\v \x01(\bH\x03R\n" +
	"isCritical\x88\x01\x01\x1a\\\n" +
	"\x13PhaseDurationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01B\v\n" +
	"\t_deadlineB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_retry_countB\x0e\n" +
	"\f_is_critical\"\xf2\x02\n" +
	"\x10ScheduleResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.testserver.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tstarts_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x12H\n" +
	"\x12estimated_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x11estimatedDuration\x12A\n" +
	"\x11assigned_priority\x18\x06 \x01(\x0e2\x14.testserver.PriorityR\x10assignedPriority\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage*I\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02\x12\f\n" +
	"\bINACTIVE\x10\x03\x12\v\n" +
	"\aDELETED\x10\x04*7\n" +
	"\bPriority\x12\a\n" +
	"\x03LOW\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x032\x8c\x04\n" +
	"\vTestService\x12C\n" +
	"\n" +
	"SimpleCall\x12\x19.testserver.SimpleRequest\x1a\x1a.testserver.SimpleResponse\x12F\n" +
	"\vComplexCall\x12\x1a.testserver.ComplexRequest\x1a\x1b.testserver.ComplexResponse\x12@\n" +
	"\tEmptyCall\x12\x18.testserver.EmptyRequest\x1a\x19.testserver.EmptyResponse\x12I\n" +
	"\fScheduleTask\x12\x1b.testserver.ScheduleRequest\x1a\x1c.testserver.ScheduleResponse\x12G\n" +
	"\fServerStream\x12\x19.testserver.SimpleRequest\x1a\x1a.testserver.StreamResponse0\x01\x12H\n" +
	"\fClientStream\x12\x19.testserver.StreamRequest\x1a\x1b.testserver.ComplexResponse(\x01\x12P\n" +
	"\x13BidirectionalStream\x12\x19.testserver.StreamRequest\x1a\x1a.testserver.StreamResponse(\x010\x012\xd3\x01\n" +
	"\x0eAnotherService\x126\n" +
	"\aGetUser\x12\x19.testserver.SimpleRequest\x1a\x10.testserver.User\x12A\n" +
	"\bGetUsers\x12\x18.testserver.EmptyRequest\x1a\x1b.testserver.ComplexResponse\x12F\n" +
	"\fUpdateStatus\x12\x1a.testserver.ComplexRequest\x1a\x1a.testserver.SimpleResponseB\x1bZ\x19grpc-gui/testserver/protob\x06proto3"

var (
	file_proto_test_proto_rawDescOnce sync.Once
	file_proto_test_proto_rawDescData []byte
)

func file_proto_test_proto_rawDescGZIP() []byte {
	file_proto_test_proto_rawDescOnce.Do(func() {
		file_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_test_proto_rawDesc), len(file_proto_test_proto_rawDesc)))
	})
	return file_proto_test_proto_rawDescData
}

var file_proto_test_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_test_proto_goTypes = []any{
	(Status)(0),                   // 0: testserver.Status
	(Priority)(0),                 // 1: testserver.Priority
	(*Address)(nil),               // 2: testserver.Address
	(*User)(nil),                  // 3: testserver.User
	(*NestedMessage)(nil),         // 4: testserver.NestedMessage
	(*ComplexRequest)(nil),        // 5: testserver.ComplexRequest
	(*ComplexResponse)(nil),       // 6: testserver.ComplexResponse
	(*SimpleRequest)(nil),         // 7: testserver.SimpleRequest
	(*SimpleResponse)(nil),        // 8: testserver.SimpleResponse
	(*StreamRequest)(nil),         // 9: testserver.StreamRequest
	(*StreamResponse)(nil),        // 10: testserver.StreamResponse
	(*EmptyRequest)(nil),          // 11: testserver.EmptyRequest
	(*EmptyResponse)(nil),         // 12: testserver.EmptyResponse
	(*ScheduleRequest)(nil),       // 13: testserver.ScheduleRequest
	(*ScheduleResponse)(nil),      // 14: testserver.ScheduleResponse
	nil,                           // 15: testserver.User.MetadataEntry
	nil,                           // 16: testserver.User.AddressMapEntry
	nil,                           // 17: testserver.ComplexRequest.UserMapEntry
	nil,                           // 18: testserver.ComplexRequest.StatusMapEntry
	nil,                           // 19: testserver.ComplexRequest.IdToNameEntry
	nil,                           // 20: testserver.ComplexResponse.ResultsEntry
	nil,                           // 21: testserver.ComplexResponse.NodesEntry
	nil,                           // 22: testserver.ScheduleRequest.PhaseDurationsEntry
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 24: google.protobuf.Duration
}
var file_proto_test_proto_depIdxs = []int32{
	0,  // 0: testserver.User.status:type_name -> testserver.Status
	2,  // 1: testserver.User.address:type_name -> testserver.Address
	15, // 2: testserver.User.metadata:type_name -> testserver.User.MetadataEntry
	16, // 3: testserver.User.address_map:type_name -> testserver.User.AddressMapEntry
	2,  // 4: testserver.User.addresses:type_name -> testserver.Address
	4,  // 5: testserver.NestedMessage.nested:type_name -> testserver.NestedMessage
	4,  // 6: testserver.NestedMessage.children:type_name -> testserver.NestedMessage
	3,  // 7: testserver.ComplexRequest.user:type_name -> testserver.User
	3,  // 8: testserver.ComplexRequest.users:type_name -> testserver.User
	17, // 9: testserver.ComplexRequest.user_map:type_name -> testserver.ComplexRequest.UserMapEntry
	4,  // 10: testserver.ComplexRequest.nested:type_name -> testserver.NestedMessage
	0,  // 11: testserver.ComplexRequest.status:type_name -> testserver.Status
	0,  // 12: testserver.ComplexRequest.statuses:type_name -> testserver.Status
	18, // 13: testserver.ComplexRequest.status_map:type_name -> testserver.ComplexRequest.StatusMapEntry
	3,  // 14: testserver.ComplexRequest.user_payload:type_name -> testserver.User
	19, // 15: testserver.ComplexRequest.id_to_name:type_name -> testserver.ComplexRequest.IdToNameEntry
	3,  // 16: testserver.ComplexResponse.user:type_name -> testserver.User
	3,  // 17: testserver.ComplexResponse.users:type_name -> testserver.User
	20, // 18: testserver.ComplexResponse.results:type_name -> testserver.ComplexResponse.ResultsEntry
	0,  // 19: testserver.ComplexResponse.status:type_name -> testserver.Status
	4,  // 20: testserver.ComplexResponse.nested:type_name -> testserver.NestedMessage
	4,  // 21: testserver.ComplexResponse.tree:type_name -> testserver.NestedMessage
	21, // 22: testserver.ComplexResponse.nodes:type_name -> testserver.ComplexResponse.NodesEntry
	0,  // 23: testserver.StreamResponse.status:type_name -> testserver.Status
	1,  // 24: testserver.ScheduleRequest.priority:type_name -> testserver.Priority
	23, // 25: testserver.ScheduleRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	24, // 26: testserver.ScheduleRequest.timeout:type_name -> google.protobuf.Duration
	23, // 27: testserver.ScheduleRequest.deadline:type_name -> google.protobuf.Timestamp
	0,  // 28: testserver.ScheduleRequest.status:type_name -> testserver.Status
	23, // 29: testserver.ScheduleRequest.checkpoints:type_name -> google.protobuf.Timestamp
	22, // 30: testserver.ScheduleRequest.phase_durations:type_name -> testserver.ScheduleRequest.PhaseDurationsEntry
	0,  // 31: testserver.ScheduleResponse.status:type_name -> testserver.Status
	23, // 32: testserver.ScheduleResponse.created_at:type_name -> google.protobuf.Timestamp
	23, // 33: testserver.ScheduleResponse.starts_at:type_name -> google.protobuf.Timestamp
	24, // 34: testserver.ScheduleResponse.estimated_duration:type_name -> google.protobuf.Duration
	1,  // 35: testserver.ScheduleResponse.assigned_priority:type_name -> testserver.Priority
	2,  // 36: testserver.User.AddressMapEntry.value:type_name -> testserver.Address
	3,  // 37: testserver.ComplexRequest.UserMapEntry.value:type_name -> testserver.User
	0,  // 38: testserver.ComplexRequest.StatusMapEntry.value:type_name -> testserver.Status
	3,  // 39: testserver.ComplexResponse.ResultsEntry.value:type_name -> testserver.User
	4,  // 40: testserver.ComplexResponse.NodesEntry.value:type_name -> testserver.NestedMessage
	24, // 41: testserver.ScheduleRequest.PhaseDurationsEntry.value:type_name -> google.protobuf.Duration
	7,  // 42: testserver.TestService.SimpleCall:input_type -> testserver.SimpleRequest
	5,  // 43: testserver.TestService.ComplexCall:input_type -> testserver.ComplexRequest
	11, // 44: testserver.TestService.EmptyCall:input_type -> testserver.EmptyRequest
	13, // 45: testserver.TestService.ScheduleTask:input_type -> testserver.ScheduleRequest
	7,  // 46: testserver.TestService.ServerStream:input_type -> testserver.SimpleRequest
	9,  // 47: testserver.TestService.ClientStream:input_type -> testserver.StreamRequest
	9,  // 48: testserver.TestService.BidirectionalStream:input_type -> testserver.StreamRequest
	7,  // 49: testserver.AnotherService.GetUser:input_type -> testserver.SimpleRequest
	11, // 50: testserver.AnotherService.GetUsers:input_type -> testserver.EmptyRequest
	5,  // 51: testserver.AnotherService.UpdateStatus:input_type -> testserver.ComplexRequest
	8,  // 52: testserver.TestService.SimpleCall:output_type -> testserver.SimpleResponse
	6,  // 53: testserver.TestService.ComplexCall:output_type -> testserver.ComplexResponse
	12, // 54: testserver.TestService.EmptyCall:output_type -> testserver.EmptyResponse
	14, // 55: testserver.TestService.ScheduleTask:output_type -> testserver.ScheduleResponse
	10, // 56: testserver.TestService.ServerStream:output_type -> testserver.StreamResponse
	6,  // 57: testserver.TestService.ClientStream:output_type -> testserver.ComplexResponse
	10, // 58: testserver.TestService.BidirectionalStream:output_type -> testserver.StreamResponse
	3,  // 59: testserver.AnotherService.GetUser:output_type -> testserver.User
	6,  // 60: testserver.AnotherService.GetUsers:output_type -> testserver.ComplexResponse
	8,  // 61: testserver.AnotherService.UpdateStatus:output_type -> testserver.SimpleResponse
	52, // [52:62] is the sub-list for method output_type
	42, // [42:52] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_proto_test_proto_init() }
func file_proto_test_proto_init() {
	if File_proto_test_proto != nil {
		return
	}
	file_proto_test_proto_msgTypes[3].OneofWrappers = []any{
		(*ComplexRequest_Text)(nil),
		(*ComplexRequest_Number)(nil),
		(*ComplexRequest_UserPayload)(nil),
	}
	file_proto_test_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_test_proto_rawDesc), len(file_proto_test_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_test_proto_goTypes,
		DependencyIndexes: file_proto_test_proto_depIdxs,
		EnumInfos:         file_proto_test_proto_enumTypes,
		MessageInfos:      file_proto_test_proto_msgTypes,
	}.Build()
	File_proto_test_proto = out.File
	file_proto_test_proto_goTypes = nil
	file_proto_test_proto_depIdxs = nil
}
