// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export interface Server {
    "id": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "deletedAt"?: gorm$0.DeletedAt;
    "name": string;
    "address": string;
    "optUseTLS": boolean;
    "optInsecure": boolean;
}
