// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

export interface EnumValueInfo {
    "name": string;
    "number": number;
}

export interface FieldInfo {
    "name": string;
    "type": string;
    "number": number;
    "repeated": boolean;
    "optional": boolean;
    "required": boolean;
    "isMap": boolean;
    "isEnum": boolean;
    "isWellKnown": boolean;
    "wellKnownType"?: string;
    "mapKey": string;
    "mapValue": string;
    "oneofGroup"?: string;
    "message"?: MessageInfo | null;
    "enumValues"?: EnumValueInfo[] | null;
}

export interface MessageInfo {
    "name": string;
    "fields": FieldInfo[] | null;
}

export interface MethodInfo {
    "name": string;
    "requestType": string;
    "responseType": string;
    "request"?: MessageInfo | null;
    "response"?: MessageInfo | null;
    "requestExample"?: json$0.RawMessage;
    "requestExampleString"?: string;
    "responseExample"?: json$0.RawMessage;
    "requestSchema"?: json$0.RawMessage;
}

export interface ServiceInfo {
    "name": string;
    "methods": MethodInfo[] | null;
}

export interface ServicesInfo {
    "services": ServiceInfo[] | null;
}
