// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EnumValueInfo {
    "name": string;
    "number": number;
}

export interface FieldInfo {
    "name": string;
    "type": string;
    "number": number;
    "repeated": boolean;
    "optional": boolean;
    "required": boolean;
    "isMap": boolean;
    "isEnum": boolean;
    "mapKey": string;
    "mapValue": string;
    "message"?: MessageInfo | null;
    "enumValues"?: EnumValueInfo[] | null;
}

export interface MessageInfo {
    "name": string;
    "fields": FieldInfo[] | null;
}
